### ISSUE TITLE
Compilation with gcc 13.2.1

### ISSUE THREAD

**Issue by LesTuche** [qcscine/molassembler#14]
Hi
Molassembler does not compile with GCC 13.2.1 I needed to include `<cstdint> `in /molassembler/src/Molassembler/IO/BinaryHandler.h and /molassembler/src/Molassembler/IO/Base64.h       

Best regards
Joël Landis

**Comment by weymutht** [comment]
Thanks for letting us know! We'll gladly incorporate these changes.

**Comment by weymutht** [comment]
The changes are available in Molassembler 3.0.0, released today.
