### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [qcscine/molassembler#15]
molassembler/src/Molassembler/IO/Base64.h:23:43: error: ‘uint8_t’ is not a member of ‘std’; did you mean ‘wint_t’?
   23 | std::string encode(const std::vector<std::uint8_t>& inputBuffer);

**Comment by weymutht** [comment]
Thanks a lot for reporting this. Could you maybe share which compiler version and which operating system you're using?

**Comment by zhangfq-chemistry** [comment]
I use ubuntu24/g++. After several "#include <cstdint>" are added, there is a linker error:
[  5%] Built target symspg_objects
[ 11%] Built target yaml-cpp
[ 47%] Built target UtilsOS
[ 47%] Built target Core
[ 49%] Built target UtilsOSModule
[ 49%] Built target gtest
[ 49%] Built target gmock
[ 50%] Built target gtest_main
[ 71%] Built target UtilsOS_tests
[ 72%] Built target SampleModule
[ 72%] Built target CoreTests
[ 73%] Built target gmock_main
[ 73%] Built target parse
[ 73%] Built target sandbox
[ 74%] Built target read
[ 89%] Built target molassembler_obj
[ 90%] Built target Molassembler
make[2]: *** No rule to make target 'libRingDecomposerLib.a', needed by 'test/MolassemblerTests'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:875: test/CMakeFiles/MolassemblerTests.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by weymutht** [comment]
Could you please let me know the exact version of GCC you are using? You shouldn't have any problems compiling Molassembler with GCC 10 and below (as long as C++17 is supported).

**Comment by zhangfq-chemistry** [comment]
gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4)
one error: molassembler/build/googletest-src/googletest/src/gtest-death-test.cc line 1299:   change to int dummy=0;
OK now!

**Comment by weymutht** [comment]
Great, thanks!
