### ISSUE TITLE
a problem occured while compare two structures

### ISSUE THREAD

**Issue by maoxinxina** [qcscine/molassembler#16]
when I tried to compare two structures, the results is same. However, there is some differences between them. So I wonder is there some adjusts need to fix this problem.

the results:
Atom stereopermutators in file 1:
5: bent, AB, 0 (1)
3: triangle, ABC, 0 (1)
0: triangle, AAB, 0 (1)

Atom stereopermutators in file 2:
5: bent, AB, 0 (1)
3: triangle, ABC, 0 (1)
0: triangle, AAB, 0 (1)

Bond stereopermutators in file 1:

Bond stereopermutators in file 2:

The component AtomEnvironmentComponents.BondOrders is the same between the two molecules.

The component AtomEnvironmentComponents.Connectivity is the same between the two molecules.

The component AtomEnvironmentComponents.ElementTypes is the same between the two molecules.

The component AtomEnvironmentComponents.ElementsAndBonds is the same between the two molecules.

The component AtomEnvironmentComponents.ElementsBondsAndShapes is the same between the two molecules.

The component AtomEnvironmentComponents.Shapes is the same between the two molecules.

The component AtomEnvironmentComponents.Stereopermutations is the same between the two molecules.

The component AtomEnvironmentComponents.All is the same between the two molecules.
![屏幕截图 2024-08-21 150017](https://github.com/user-attachments/assets/fdf0acdb-54f3-4770-a466-d111751bbd94)
![屏幕截图 2024-08-21 150037](https://github.com/user-attachments/assets/1f4f7a3f-2642-40a5-99aa-fc42e2a086db)

**Comment by weymutht** [comment]
For Molassembler, these are just two conformers of the same compound, which is why they are reported as being identical. This is intended behavior.

**Comment by maoxinxina** [comment]
Thank you, I understand.
